# * UMASK_SET=022 suelen definirlo en los contenedores
# https://maglit.me/wachuuchochudmate - Puedes cambiar el logo en FileBroswer

# NETWORKS =======================
networks:
  default:
    name: net_dullahan
    external: true

# SERVICES =======================
services:
#
#  ___ _  _____ _______ ___ ___ ________
# / _ \ |/ / -_) __(_-</ -_) -_) __/ __/
# \___/___/\__/_/ /___/\__/\__/_/ /_/
#
  overseerr: # Media discovery tool built to work with Plex ecosystem
    container_name: Overseerr
    image: sctx/overseerr:latest
    environment:
      - LOG_LEVEL=info
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUMEN}/overseerr:/app/config
    ports:
      - "${PORT_OVERSE}:5055"
    restart: unless-stopped
#   __                          _         _
#  / /________ ____  ___ __ _  (_)__ ___ (_)__  ___
# / __/ __/ _ `/ _ \(_-</  ' \/ (_-<(_-</ / _ \/ _ \
# \__/_/  \_,_/_//_/___/_/_/_/_/___/___/_/\___/_//_/
#
  transmission: # BitTorrent client
    container_name: Transmission
    image: lscr.io/linuxserver/transmission:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - USER=admin
      - PASS=Shikimori..
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DIRDOWN}:/downloads
      - ${VOLUMEN}/transmission:/config
      - ${VOLUMEN}/transmission/torrent:/watch
    ports:
      - "${PORT_TRANSM}:9091"
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
#                         __
#    ___  _______ _    __/ /__ _________
#   / _ \/ __/ _ \ |/|/ / / _ `/ __/ __/
#  / .__/_/  \___/__,__/_/\_,_/_/ /_/
# /_/
  prowlarr: # Indexer manager for Sonarr & Radarr
    container_name: Prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUMEN}/prowlarr:/config
    ports:
      - "${PORT_PROWLA}:9696"
    restart: unless-stopped
#                __
#   _______ ____/ /__ _________
#  / __/ _ `/ _  / _ `/ __/ __/
# /_/  \_,_/\_,_/\_,_/_/ /_/
#
  radarr: # Sonarr, but for Movies
    container_name: Radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUMEN}/radarr:/config
      - ${DIRDOWN}:/downloads
    ports:
      - "${PORT_RADARR}:7878"
    restart: unless-stopped
#
#   ___ ___  ___  ___ _________
#  (_-</ _ \/ _ \/ _ `/ __/ __/
# /___/\___/_//_/\_,_/_/ /_/
#
  sonarr: # TV show search agent
    container_name: Sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUMEN}/sonarr:/config
      - ${DIRDOWN}/downloads
    ports:
      - "${PORT_SONARR}:8989"
    restart: unless-stopped
#    ___    __
#   / (_)__/ /__ _________
#  / / / _  / _ `/ __/ __/
# /_/_/\_,_/\_,_/_/ /_/
#
  lidarr: # Music collection manager
    container_name: Lidarr
    image: lscr.io/linuxserver/lidarr:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUMEN}/lidarr:/config
      - ${DIRDOWN}:/downloads
    ports:
      - "${PORT_LIDARR}:8686"
    restart: unless-stopped
#                 __
#   __ _  ___ ___/ /_ _____ ___ _
#  /  ' \/ -_) _  / // (_-</ _ `/
# /_/_/_/\__/\_,_/\_,_/___/\_,_/
#
  medusa: # Automatic video library manager for TV Shows
    container_name: Medusa
    image: lscr.io/linuxserver/medusa:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUMEN}/medusa:/config
      - ${DIRDOWN}:/downloads
    ports:
      - "${PORT_MEDUSA}:8081"
    restart: unless-stopped
#    _____                      __
#   / _/ /__ ________ ___ ___  / /  _____ ________
#  / _/ / _ `/ __/ -_|_-</ _ \/ / |/ / -_) __/ __/
# /_//_/\_,_/_/  \__/___/\___/_/|___/\__/_/ /_/
#
  flaresolverr: # Proxy server to bypass Cloudflare protection
    container_name: FlareSolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - LOG_HTML=${LOG_HTML:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - TEST_URL="https://www.debian.org"
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${PORT_FLARES}:8191"
    restart: unless-stopped
#    __       _          __     ____
#   / /  ___ (_)_ _  ___/ /__ _/ / /
#  / _ \/ -_) /  ' \/ _  / _ `/ / /
# /_//_/\__/_/_/_/_/\_,_/\_,_/_/_/
#
  heimdall: # Dashboard for all web application
    container_name: Heimdall
    image: lscr.io/linuxserver/heimdall:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUMEN}/heimdall:/config
    ports:
      - "${PORT_HEIMDA}:80"
      - "443:443"
    restart: unless-stopped
#    ____ __    __
#   / _(_) /__ / /  _______ _    _____ ___ ____
#  / _/ / / -_) _ \/ __/ _ \ |/|/ (_-</ -_) __/
# /_//_/_/\__/_.__/_/  \___/__,__/___/\__/_/
#
  file-browser: # File management interface
    container_name: FileBrowser
    image: filebrowser/filebrowser:latest
    user: ${UID}:${GID}
    volumes:
      - ${DIRDOWN}:/srv
      - ${VOLUMEN}/filebrowser/database.db:/database.db
    ports:
      - "${PORT_FILEBR}:80"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped